### ISSUE TITLE
Get Code Climate GPA to at LEAST a 3.5

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/king-tide#1]
As of right now it's a 0.2 GPA :(

**Comment by yamilethmedina** [comment]
We're currently at 3.3. We'll get there soon :)

**Comment by yamilethmedina** [comment]
It's 3.62 now! 😺  There are still some minor fixes to make, but close if you want.

**Comment by ErnieAtLYD** [comment]
YAAAAAAAAAAYYYYYYY
