### ISSUE TITLE
Uploads Not appearing in admin panel

### ISSUE THREAD

**Issue by susanfiu** [Code-for-Miami/king-tide#13]
I tried uploading reports a couple of times today. First time received a message that all was OK, second time got an error. I repeated it this evening with the same results. Below is a description with screenshots:

*Uploaded report and photos from laptop. received message that all was OK.
*Uploaded report and photos from phone, received message of an error.

Here are screenshots.
<img width="1440" alt="screen shot 2017-09-02 at 8 11 31 pm" src="https://user-images.githubusercontent.com/5581312/29999591-9b02c926-901c-11e7-9215-256c8e908320.png">
![21231651_10105622075352803_4722957962675816224_n](https://user-images.githubusercontent.com/5581312/29999592-9f541b4c-901c-11e7-9c50-c16c8d7c4e8c.jpg)

**Comment by yamilethmedina** [comment]
Let me check the logs in a bit to see what the issue could be.

**Comment by ErnieAtLYD** [comment]
@yamilethmedina is this a bug?

**Comment by differentsmoke** [comment]
I'm going to go ahead and assume this was fixed! Hope you don't mind
