### ISSUE TITLE
https://www.floodform.com/pages/locations goes to Error 500

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/king-tide#18]
Step: go to https://www.floodform.com/pages/locations

Result: You get the following message -
"We're sorry, but something went wrong. If you are the application owner check the logs for more information."

**Comment by susanfiu** [comment]
Location should go away. I am working on a new set of instructions.

**Comment by differentsmoke** [comment]
This was fixed for instructions and the locations page was removed. I am now working on adding the new instructions.
