### ISSUE TITLE
missing region; use :region option or export region name to ENV['AWS_REGION']

### ISSUE THREAD

**Issue by differentsmoke** [Code-for-Miami/king-tide#24]
I'm having this issue when trying to create a flood on my local machine.

I have an idea of where the issue is, but before I wanted to clarify whether this is an issue with the project or with my local installation.

@CyberStrike  and @yamilethmedina I'm just assigning you to confirm that you are having the issue or not, in the latest version. Thanks.

**Comment by CyberStrike** [comment]
@differentsmoke Steps to reproduce?

**Comment by differentsmoke** [comment]
Add a new flood on the form, on the dev environment.

**Comment by CyberStrike** [comment]
Steps to reproduce, in development.

1. Visit project root `/`
2. Enter random values into flood form.
3. Attach an image to form.
4. Submit
5. Receive Error.

```sh
Aws::Errors::MissingRegionError - missing region; use :region option or export region name to ENV['AWS_REGION']:
  aws-sdk-core (2.10.52) lib/aws-sdk-core/plugins/regional_endpoint.rb:34:in `after_initialize'
  aws-sdk-core (2.10.52) lib/seahorse/client/base.rb:84:in `block in after_initialize'
  aws-sdk-core (2.10.52) lib/seahorse/client/base.rb:83:in `after_initialize'
  aws-sdk-core (2.10.52) lib/seahorse/client/base.rb:21:in `initialize'
  aws-sdk-core (2.10.52) lib/seahorse/client/base.rb:105:in `new'
  aws-sdk-resources (2.10.52) lib/aws-sdk-resources/resource.rb:169:in `extract_client'
  aws-sdk-resources (2.10.52) lib/aws-sdk-resources/resource.rb:15:in `initialize'
  paperclip (5.0.0) lib/paperclip/storage/s3.rb:247:in `obtain_s3_instance_for'
  paperclip (5.0.0) lib/paperclip/storage/s3.rb:241:in `s3_interface'
  paperclip (5.0.0) lib/paperclip/storage/s3.rb:251:in `s3_bucket'
  paperclip (5.0.0) lib/paperclip/storage/s3.rb:259:in `s3_object'
  paperclip (5.0.0) lib/paperclip/storage/s3.rb:361:in `block in flush_writes'
  paperclip (5.0.0) lib/paperclip/storage/s3.rb:334:in `flush_writes'
  paperclip (5.0.0) lib/paperclip/attachment.rb:241:in `save'
  paperclip (5.0.0) lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'
```

**Comment by CyberStrike** [comment]
@differentsmoke bug reproduced. A solution would be to toggle to file storage for Paperclip in dev?

**Comment by differentsmoke** [comment]
Ok, so basically I wanted to make sure that paperclip **wasn't** enabled on dev, and it wasn't just that I had not set it up properly. On it.

**Comment by CyberStrike** [comment]
@differentsmoke We do want paperclip to work on dev, but it shouldn't be storing on a S3 Bucket, it should store to the local file system.

**Comment by differentsmoke** [comment]
I fixed this on branch form-changes. For some reason, AWS credentials were present both on the environment.rb file and also on the individual models that used paperclip attachments.
