### ISSUE TITLE
King Tide Dev

### ISSUE THREAD

**Issue by differentsmoke** [Code-for-Miami/king-tide#27]
Due to the specific gotchas of running the app on Heroku vs locally, and also considering the difference between using AWS and local storage for attachment, I created a "dev" app on Heroku so we can preview an test features there safely without compromising floodform.com.

https://king-tide-dev.herokuapp.com/

(fun fact: it was immediately broken due to something that was working on my local dev environment)

This app has it's own (less powerful) database but IT **SHARES THE SAME AWS CREDENTIALS**, so it will store images on the same bucket. @CyberStrike , do you think this would be a problem?

@susanfiu @thejuliekramer @bofill @yamilethmedina 

(Right now you'll see a diminished form on it, because I'm trying to change how we submit salinity and depth.)

**Comment by susanfiu** [comment]
Hi there,
We may need a new Google Map API Key? 
sj

**Comment by differentsmoke** [comment]
Good point 😬

**Comment by CyberStrike** [comment]
@differentsmoke Using the aws credentials are ok. Can you give CodeFormMiami@Gmail.com access to that heroku app so I can add it to the [heroku pipeline](https://devcenter.heroku.com/articles/pipelines).

**Comment by differentsmoke** [comment]
Ok. CodeForMiami user was added and the map is using my own personal googlemaps API key.

**Comment by CyberStrike** [comment]
@differentsmoke I don't see anything on the CodeForMiami heroku account

**Comment by differentsmoke** [comment]
There was an extra M in the email I copy and pasted. Now it should work.
