### ISSUE TITLE
Shut down Digital Ocean instance

### ISSUE THREAD

**Issue by yamilethmedina** [Code-for-Miami/king-tide#33]
So sad to have missed Sea Level Rise solutions day - I had a workshop conflicting and have been very busy with work lately. I don't think I can make it tonight (and forgot my laptop, booo), but wanted to ask if it would be OK to shut down the Digital Ocean droplet we've been using for this, on localwarmingfloodform.us.

It appears that the app is now being hosted on Bluehost (yay!). I'd have no problem continuing to pay the $5 monthly if we needed it, but it seems like we no longer do.

Also, since it now has a better URL, i'm planning to let the domain name expire when it's scheduled to in March/April. 

Please let me know if you guys have any concerns!

**Comment by yamilethmedina** [comment]
BTW I allowed the Let's Encrypt SSL certificate expire over the weekend for this reason; seems like it wasn't needed anymore either.

**Comment by CyberStrike** [comment]
I believe it should be ok since everything switched over to https://www.floodform.com/

**Comment by differentsmoke** [comment]
Who would be able to shut up the Digital Ocean thing? @yamilethmedina  @CyberStrike  ?

**Comment by differentsmoke** [comment]
Was this done? @yamilethmedina @CyberStrike

**Comment by yamilethmedina** [comment]
Yes, the droplet's dead :) @differentsmoke @CyberStrike
