### ISSUE TITLE
https://www.localwarmingkingtideform.us returning error

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/king-tide#4]
It's returning an Error 500 for me.

**Comment by yamilethmedina** [comment]
that was happening yesterday but i seemed to fix the situation. seems to be happening again :( i'll figure it out.

**Comment by yamilethmedina** [comment]
The server went down again (the process probably just shut down), and I had to kill some processes. I restarted the server over SSH and the site is working again.

However, i'm looking into better deployment practices and possible scripts that will restart the Rails Puma server if it shuts down for any reason.

**Comment by CyberStrike** [comment]
@yamilethmedina Can you make an issue that explains the deployment issue and possible solutions?
