### ISSUE TITLE
Merge Will It Flood into King Tide Form

### ISSUE THREAD

**Issue by CyberStrike** [Code-for-Miami/king-tide#5]
Add will it flood assets to the project. After a lengthy discussion we have opted to just copy the project files over instead of using [Git Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)

[Will It Flood](https://github.com/Code-for-Miami/When-Will-It-Flood-)

**Comment by yamilethmedina** [comment]
@CyberStrike would someone like to create a branch for this?

**Comment by CyberStrike** [comment]
@yamilethmedina I'll start tackling this when I get there.
