### ISSUE TITLE
Deployment process improvements

### ISSUE THREAD

**Issue by yamilethmedina** [Code-for-Miami/king-tide#7]
Currently, deployment is done by ssh-ing into the server, shutting down Rails, pulling updates from the Git repo, and then starting the Rails/Puma server again (while binding it to the DigitalOcean IP address).

1. ssh root@45.55.140.38
2. cd opendataday2017
3. git pull
4. nohup long-running-command & rails s Puma --binding=45.55.140.38

This isn't ideal for several reasons. Most significantly, if the server crashes for any reason, it won't restart. That means the site stays down until someone notices and logs in to do it manually.

Some sort of automatic deployment would be great!

@CyberStrike

**Comment by CyberStrike** [comment]
Moved to heroku so I think we can consider this closed?
